[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bollywood-song-recommender"
version = "1.0.0"
description = "A Bollywood song recommendation system"
requires-python = ">=3.10,<3.11" 